import http from '../http'

export const getStoreList = (params?: any) => http.get('/retail/store/index', { params })
export const createStore = (data: any) => http.post('/retail/store/add', data)
export const updateStore = (data: any) => http.post('/retail/store/edit', data)
export const deleteStore = (id: number) => http.post('/retail/store/del', { id })
export const getRetailOrderList = (params?: any) => http.get('/retail/order/index', { params })
export const createRetailOrder = (data: any) => http.post('/retail/order/add', data)
export const updateRetailOrder = (data: any) => http.post('/retail/order/edit', data)
export const deleteRetailOrder = (id: number) => http.post('/retail/order/del', { id })
export const getRetailReturnList = (params?: any) => http.get('/retail/return/index', { params })
export const createRetailReturn = (data: any) => http.post('/retail/return/add', data)
export const deleteRetailReturn = (id: number) => http.post('/retail/return/del', { id })
export const auditRetailReturn = (id: number, status: number) => http.post('/retail/return/edit', { id, status })
export const getMemberList = (params?: any) => http.get('/retail/member/index', { params })
export const createMember = (data: any) => http.post('/retail/member/add', data)
export const updateMember = (data: any) => http.post('/retail/member/edit', data)
export const deleteMember = (id: number) => http.post('/retail/member/del', { id })
export const getRechargeList = (params?: any) => http.get('/retail/recharge/index', { params })
export const createRecharge = (data: any) => http.post('/retail/recharge/add', data)
export const deleteRecharge = (id: number) => http.post('/retail/recharge/del', { id })
export const getPointsList = (params?: any) => http.get('/retail/points/index', { params })
export const getCouponList = (params?: any) => http.get('/retail/coupon/index', { params })
export const createCoupon = (data: any) => http.post('/retail/coupon/add', data)
export const updateCoupon = (data: any) => http.post('/retail/coupon/edit', data)
export const deleteCoupon = (id: number) => http.post('/retail/coupon/del', { id })
