import http from '../http'

export const getOutsourcePlanList = (params?: any) => http.get('/outsource/plan/index', { params })
export const createOutsourcePlan = (data: any) => http.post('/outsource/plan/add', data)
export const updateOutsourcePlan = (data: any) => http.post('/outsource/plan/edit', data)
export const deleteOutsourcePlan = (id: number) => http.post('/outsource/plan/del', { id })
export const getOutsourceInhouseList = (params?: any) => http.get('/outsource/inhouse/index', { params })
export const createOutsourceInhouse = (data: any) => http.post('/outsource/inhouse/add', data)
export const deleteOutsourceInhouse = (id: number) => http.post('/outsource/inhouse/del', { id })
export const getReceiveList = (params?: any) => http.get('/outsource/receive/index', { params })
export const createReceive = (data: any) => http.post('/outsource/receive/add', data)
export const deleteReceive = (id: number) => http.post('/outsource/receive/del', { id })
export const getQualityList = (params?: any) => http.get('/outsource/quality/index', { params })
export const createQuality = (data: any) => http.post('/outsource/quality/add', data)
export const deleteQuality = (id: number) => http.post('/outsource/quality/del', { id })
export const getOutsourcePayableList = (params?: any) => http.get('/outsource/payable/index', { params })
export const createOutsourcePayable = (data: any) => http.post('/outsource/payable/add', data)
export const deleteOutsourcePayable = (id: number) => http.post('/outsource/payable/del', { id })
export const getOutsourcePaymentList = (params?: any) => http.get('/outsource/payment/index', { params })
export const createOutsourcePayment = (data: any) => http.post('/outsource/payment/add', data)
export const deleteOutsourcePayment = (id: number) => http.post('/outsource/payment/del', { id })
