import http from '../http'

export const getSalaryList = (params?: any) => http.get('/personnel/salary/index', { params })
export const createSalary = (data: any) => http.post('/personnel/salary/add', data)
export const deleteSalary = (id: number) => http.post('/personnel/salary/del', { id })
export const getJobChangeList = (params?: any) => http.get('/personnel/jobChange/index', { params })
export const createJobChange = (data: any) => http.post('/personnel/jobChange/add', data)
export const deleteJobChange = (id: number) => http.post('/personnel/jobChange/del', { id })
export const getResignList = (params?: any) => http.get('/personnel/resign/index', { params })
export const createResign = (data: any) => http.post('/personnel/resign/add', data)
export const deleteResign = (id: number) => http.post('/personnel/resign/del', { id })
export const getCarList = (params?: any) => http.get('/personnel/car/index', { params })
export const createCar = (data: any) => http.post('/personnel/car/add', data)
export const updateCar = (data: any) => http.post('/personnel/car/edit', data)
export const deleteCar = (id: number) => http.post('/personnel/car/del', { id })
export const getAttendanceList = (params?: any) => http.get('/personnel/attendance/index', { params })
export const createAttendance = (data: any) => http.post('/personnel/attendance/add', data)
export const deleteAttendance = (id: number) => http.post('/personnel/attendance/del', { id })
export const getRecruitList = (params?: any) => http.get('/personnel/recruit/index', { params })
export const createRecruit = (data: any) => http.post('/personnel/recruit/add', data)
export const deleteRecruit = (id: number) => http.post('/personnel/recruit/del', { id })
export const getStaffList = (params?: any) => http.get('/personnel/staff/index', { params })
export const createStaff = (data: any) => http.post('/personnel/staff/add', data)
export const updateStaff = (data: any) => http.post('/personnel/staff/edit', data)
export const deleteStaff = (id: number) => http.post('/personnel/staff/del', { id })
export const getPersonnelContractList = (params?: any) => http.get('/personnel/contract/index', { params })
export const createPersonnelContract = (data: any) => http.post('/personnel/contract/add', data)
export const deletePersonnelContract = (id: number) => http.post('/personnel/contract/del', { id })
export const getSocialList = (params?: any) => http.get('/personnel/social/index', { params })
export const createSocial = (data: any) => http.post('/personnel/social/add', data)
export const deleteSocial = (id: number) => http.post('/personnel/social/del', { id })
export const getWelfareList = (params?: any) => http.get('/personnel/welfare/index', { params })
export const createWelfare = (data: any) => http.post('/personnel/welfare/add', data)
export const deleteWelfare = (id: number) => http.post('/personnel/welfare/del', { id })
