import http from '../http'

export const getDeptList = (params?: any) => http.get('/setting/dept/index', { params })
export const createDept = (data: any) => http.post('/setting/dept/add', data)
export const updateDept = (data: any) => http.post('/setting/dept/edit', data)
export const deleteDept = (id: number) => http.post('/setting/dept/del', { id })
export const getRoleList = (params?: any) => http.get('/setting/role/index', { params })
export const createRole = (data: any) => http.post('/setting/role/add', data)
export const updateRole = (data: any) => http.post('/setting/role/edit', data)
export const deleteRole = (id: number) => http.post('/setting/role/del', { id })
export const getJobsList = (params?: any) => http.get('/setting/jobs/index', { params })
export const createJobs = (data: any) => http.post('/setting/jobs/add', data)
export const updateJobs = (data: any) => http.post('/setting/jobs/edit', data)
export const deleteJobs = (id: number) => http.post('/setting/jobs/del', { id })
export const getAdminList = (params?: any) => http.get('/setting/admin/index', { params })
export const createAdmin = (data: any) => http.post('/setting/admin/add', data)
export const updateAdmin = (data: any) => http.post('/setting/admin/edit', data)
export const deleteAdmin = (id: number) => http.post('/setting/admin/del', { id })
export const getParamsList = (params?: any) => http.get('/setting/params/index', { params })
export const createParams = (data: any) => http.post('/setting/params/add', data)
export const updateParams = (data: any) => http.post('/setting/params/edit', data)
export const getOperationLogList = (params?: any) => http.get('/setting/operationLog/index', { params })
export const getCompanyInfo = () => http.get('/setting/company/detail')
export const updateCompanyInfo = (data: any) => http.post('/setting/company/edit', data)
export const getPrintList = (params?: any) => http.get('/setting/print/index', { params })
