import http from '../http'

export const getTaskList = (params?: any) => http.get('/office/task/index', { params })
export const createTask = (data: any) => http.post('/office/task/add', data)
export const updateTask = (data: any) => http.post('/office/task/edit', data)
export const deleteTask = (id: number) => http.post('/office/task/del', { id })
export const getCloudList = (params?: any) => http.get('/office/cloud/index', { params })
export const createCloud = (data: any) => http.post('/office/cloud/add', data)
export const deleteCloud = (id: number) => http.post('/office/cloud/del', { id })
export const getRemindList = (params?: any) => http.get('/office/remind/index', { params })
export const createRemind = (data: any) => http.post('/office/remind/add', data)
export const deleteRemind = (id: number) => http.post('/office/remind/del', { id })
export const getNoticeList = (params?: any) => http.get('/office/notice/index', { params })
export const createNotice = (data: any) => http.post('/office/notice/add', data)
export const updateNotice = (data: any) => http.post('/office/notice/edit', data)
export const deleteNotice = (id: number) => http.post('/office/notice/del', { id })
export const getApprovalList = (params?: any) => http.get('/office/approval/index', { params })
export const createApproval = (data: any) => http.post('/office/approval/add', data)
export const deleteApproval = (id: number) => http.post('/office/approval/del', { id })
export const getWorkReportList = (params?: any) => http.get('/office/workReport/index', { params })
export const createWorkReport = (data: any) => http.post('/office/workReport/add', data)
export const deleteWorkReport = (id: number) => http.post('/office/workReport/del', { id })
export const getVisitList = (params?: any) => http.get('/office/visit/index', { params })
export const createVisit = (data: any) => http.post('/office/visit/add', data)
export const deleteVisit = (id: number) => http.post('/office/visit/del', { id })
export const getOfficeExpenseList = (params?: any) => http.get('/office/expense/index', { params })
export const createOfficeExpense = (data: any) => http.post('/office/expense/add', data)
export const deleteOfficeExpense = (id: number) => http.post('/office/expense/del', { id })
export const getLeaveList = (params?: any) => http.get('/office/leave/index', { params })
export const createLeave = (data: any) => http.post('/office/leave/add', data)
export const deleteLeave = (id: number) => http.post('/office/leave/del', { id })
export const getOvertimeList = (params?: any) => http.get('/office/overtime/index', { params })
export const createOvertime = (data: any) => http.post('/office/overtime/add', data)
export const deleteOvertime = (id: number) => http.post('/office/overtime/del', { id })
export const getBusinessList = (params?: any) => http.get('/office/business/index', { params })
export const createBusiness = (data: any) => http.post('/office/business/add', data)
export const deleteBusiness = (id: number) => http.post('/office/business/del', { id })
