/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdamChat: typeof import('./components/AdamChat.vue')['default']
    AgentChat: typeof import('./components/agent/AgentChat.vue')['default']
    AgentLiveFeed: typeof import('./components/agent/AgentLiveFeed.vue')['default']
    AgentOnboardingGuide: typeof import('./components/AgentOnboardingGuide.vue')['default']
    AgentPageLayout: typeof import('./components/agent/AgentPageLayout.vue')['default']
    AiAssistant: typeof import('./components/AiAssistant.vue')['default']
    AiMemoryPanel: typeof import('./components/ai/AiMemoryPanel.vue')['default']
    AiToolCallCard: typeof import('./components/ai/AiToolCallCard.vue')['default']
    BrandCustomerService: typeof import('./components/BrandCustomerService.vue')['default']
    CaptainBar: typeof import('./components/CaptainBar.vue')['default']
    CaptchaCanvas: typeof import('./components/CaptchaCanvas.vue')['default']
    CommanderBar: typeof import('./components/CommanderBar.vue')['default']
    CustomerSelect: typeof import('./components/CustomerSelect.vue')['default']
    DeptBulletin: typeof import('./components/agent/DeptBulletin.vue')['default']
    DeptEmployeeCard: typeof import('./components/agent/DeptEmployeeCard.vue')['default']
    GoodsFormDialog: typeof import('./components/GoodsFormDialog.vue')['default']
    GoodsSelect: typeof import('./components/GoodsSelect.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageCropper: typeof import('./components/ImageCropper.vue')['default']
    OnboardingGuide: typeof import('./components/OnboardingGuide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScForm: typeof import('./components/ScForm.vue')['default']
    ScTable: typeof import('./components/ScTable.vue')['default']
    StaffSelect: typeof import('./components/StaffSelect.vue')['default']
    SupplierSelect: typeof import('./components/SupplierSelect.vue')['default']
    TrialBanner: typeof import('./components/TrialBanner.vue')['default']
    UpgradeDialog: typeof import('./components/UpgradeDialog.vue')['default']
    VoiceCallOverlay: typeof import('./components/ai/VoiceCallOverlay.vue')['default']
  }
}
