/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentChat: typeof import('./components/agent/AgentChat.vue')['default']
    AgentOnboardingGuide: typeof import('./components/AgentOnboardingGuide.vue')['default']
    AgentPageLayout: typeof import('./components/agent/AgentPageLayout.vue')['default']
    AiAssistant: typeof import('./components/AiAssistant.vue')['default']
    AiToolCallCard: typeof import('./components/ai/AiToolCallCard.vue')['default']
    CaptainBar: typeof import('./components/CaptainBar.vue')['default']
    CaptchaCanvas: typeof import('./components/CaptchaCanvas.vue')['default']
    CommanderBar: typeof import('./components/CommanderBar.vue')['default']
    CustomerSelect: typeof import('./components/CustomerSelect.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    GoodsFormDialog: typeof import('./components/GoodsFormDialog.vue')['default']
    GoodsSelect: typeof import('./components/GoodsSelect.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OnboardingGuide: typeof import('./components/OnboardingGuide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScForm: typeof import('./components/ScForm.vue')['default']
    ScTable: typeof import('./components/ScTable.vue')['default']
    StaffSelect: typeof import('./components/StaffSelect.vue')['default']
    SupplierSelect: typeof import('./components/SupplierSelect.vue')['default']
    TrialBanner: typeof import('./components/TrialBanner.vue')['default']
    UpgradeDialog: typeof import('./components/UpgradeDialog.vue')['default']
  }
}
