import http from '../http'

export const getReceivableList = (params?: any) => http.get('/finance/CollectAccounts/index', { params })
export const getPayableList = (params?: any) => http.get('/finance/PayAccounts/index', { params })
export const getCollectReceiptList = (params?: any) => http.get('/finance/CollectReceipt/index', { params })
export const createCollectReceipt = (data: any) => http.post('/finance/CollectReceipt/add', data)
export const deleteCollectReceipt = (id: number) => http.post('/finance/CollectReceipt/del', { id })
export const getPayReceiptList = (params?: any) => http.get('/finance/PayReceipt/index', { params })
export const createPayReceipt = (data: any) => http.post('/finance/PayReceipt/add', data)
export const deletePayReceipt = (id: number) => http.post('/finance/PayReceipt/del', { id })
export const getInvoiceList = (params?: any) => http.get('/finance/Invoice/index', { params })
export const createInvoice = (data: any) => http.post('/finance/Invoice/add', data)
export const deleteInvoice = (id: number) => http.post('/finance/Invoice/del', { id })
export const getStatementList = (params?: any) => http.get('/finance/Statement/index', { params })
export const createStatement = (data: any) => http.post('/finance/Statement/add', data)
export const deleteStatement = (id: number) => http.post('/finance/Statement/del', { id })
export const getExpenseList = (params?: any) => http.get('/finance/Expense/index', { params })
export const createExpense = (data: any) => http.post('/finance/Expense/add', data)
export const deleteExpense = (id: number) => http.post('/finance/Expense/del', { id })
export const getFundList = (params?: any) => http.get('/finance/Fund/index', { params })
export const createFund = (data: any) => http.post('/finance/Fund/add', data)
export const updateFund = (data: any) => http.post('/finance/Fund/edit', data)
export const deleteFund = (id: number) => http.post('/finance/Fund/del', { id })
export const getFundFlowList = (params?: any) => http.get('/finance/FundFlow/index', { params })
export const getCostList = (params?: any) => http.get('/finance/Cost/index', { params })
export const createCost = (data: any) => http.post('/finance/Cost/add', data)
export const deleteCost = (id: number) => http.post('/finance/Cost/del', { id })
